# Site
name: '최적화된 인생'
description: '최적화된 인생 블로그는 자기계발에 큰 관심과 열정을 가지고 다양한 도서를 소개하고 내용을 리뷰하여 독자분들에게 가치 있는 정보를 제공합니다.'
logo: '/assets/images/avatar1.jpg'
favicon: 'assets/images/favicon.ico'
url: "https://optlife.github.io"
baseurl: '/blog'
disqus: 'https-optlife-github-io-blog'
email: 'ayntox@gmail.com'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

locale: "ko-KR"

authors:
  OPTLIFE:
      name:           OPTLIFE
      site:           https://optlife.github.io/blog
      avatar:         /assets/images/avatar1.jpg
      bio:            "최적화된 인생 블로그는 자기계발에 큰 관심과 열정을 가지고 다양한 도서를 소개하고 내용을 리뷰하여 독자분들에게 가치 있는 정보를 제공합니다."
      email:          ayntox@gmail.com
      twitter:        https://twitter.com/ayntox
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: OPTLIFE
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10



# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules, blog.feather]
